#!/bin/bash
if [ $# -eq 0 ]
    then	
    dvbsnoop -n 10 -s ts -tssubdecode   0x201 -if sample.ts
fi
if [ $# -eq 1 ]
    then	
    dvbsnoop  -n $1 -s ts -tssubdecode   0x201 -if sample.ts
fi
if [ $# -eq 2 ]
    then	
    dvbsnoop  -nph -n $1 -s ts -tssubdecode   0x201 -if $2
fi
 
